//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoalTask.Desktop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoalTask.Desktop.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline cannot be from past..
        /// </summary>
        internal static string AddGoal_Deadline_Valid {
            get {
                return ResourceManager.GetString("AddGoal_Deadline_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Goal failed.
        /// </summary>
        internal static string AddGoal_Error_Message {
            get {
                return ResourceManager.GetString("AddGoal_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Insertion Error.
        /// </summary>
        internal static string AddGoal_Error_Message_Title {
            get {
                return ResourceManager.GetString("AddGoal_Error_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal adding failed.
        /// </summary>
        internal static string AddGoal_Fail_Message {
            get {
                return ResourceManager.GetString("AddGoal_Fail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category.
        /// </summary>
        internal static string AddGoal_GoalCategory_Select {
            get {
                return ResourceManager.GetString("AddGoal_GoalCategory_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal name cannot be empty.
        /// </summary>
        internal static string AddGoal_GoalName_Empty {
            get {
                return ResourceManager.GetString("AddGoal_GoalName_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Status of goal.
        /// </summary>
        internal static string AddGoal_GoalStatus_Select {
            get {
                return ResourceManager.GetString("AddGoal_GoalStatus_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Goal added succesfully!.
        /// </summary>
        internal static string AddGoal_Success_Message {
            get {
                return ResourceManager.GetString("AddGoal_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline cannot be from past.
        /// </summary>
        internal static string AddTask_Deadline_Valid {
            get {
                return ResourceManager.GetString("AddTask_Deadline_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Insertion Error.
        /// </summary>
        internal static string AddTask_Error_Message_Title {
            get {
                return ResourceManager.GetString("AddTask_Error_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task adding failed.
        /// </summary>
        internal static string AddTask_Fail_Message {
            get {
                return ResourceManager.GetString("AddTask_Fail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New task added succesfully.
        /// </summary>
        internal static string AddTask_Success_Message {
            get {
                return ResourceManager.GetString("AddTask_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task name cannot be empty.
        /// </summary>
        internal static string AddTask_TaskName_Empty {
            get {
                return ResourceManager.GetString("AddTask_TaskName_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Task Priority.
        /// </summary>
        internal static string AddTask_TaskPriority_Select {
            get {
                return ResourceManager.GetString("AddTask_TaskPriority_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Task Status.
        /// </summary>
        internal static string AddTask_TaskStatus_Select {
            get {
                return ResourceManager.GetString("AddTask_TaskStatus_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task closing failed.
        /// </summary>
        internal static string CloseTask_Fail_Message {
            get {
                return ResourceManager.GetString("CloseTask_Fail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task closed successfully with Today&apos;s date as closing date..
        /// </summary>
        internal static string CloseTask_Success_Message {
            get {
                return ResourceManager.GetString("CloseTask_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete?.
        /// </summary>
        internal static string Delete_Confirmation {
            get {
                return ResourceManager.GetString("Delete_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete confirmation.
        /// </summary>
        internal static string Delete_Confirmation_Title {
            get {
                return ResourceManager.GetString("Delete_Confirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal deletion failed.
        /// </summary>
        internal static string DeleteGoal_Fail_Message {
            get {
                return ResourceManager.GetString("DeleteGoal_Fail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal deleted succesfully.
        /// </summary>
        internal static string DeleteGoal_Success_Message {
            get {
                return ResourceManager.GetString("DeleteGoal_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task deletion failed.
        /// </summary>
        internal static string DeleteTask_Fail_Message {
            get {
                return ResourceManager.GetString("DeleteTask_Fail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task deleted succesfully.
        /// </summary>
        internal static string DeleteTask_Success_Message {
            get {
                return ResourceManager.GetString("DeleteTask_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Check the following.
        /// </summary>
        internal static string Error_Message_Header {
            get {
                return ResourceManager.GetString("Error_Message_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        internal static string Fail_Message_Title {
            get {
                return ResourceManager.GetString("Fail_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date cannot be before Begin Date.
        /// </summary>
        internal static string FilterGoals_DateFilter_fromto {
            get {
                return ResourceManager.GetString("FilterGoals_DateFilter_fromto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Goal found matching criteria.
        /// </summary>
        internal static string FilterGoals_NoData_Message {
            get {
                return ResourceManager.GetString("FilterGoals_NoData_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date cannot be before Begin Date.
        /// </summary>
        internal static string FilterTasks_DateFilter_fromto {
            get {
                return ResourceManager.GetString("FilterTasks_DateFilter_fromto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Task found matching criteria.
        /// </summary>
        internal static string FilterTasks_NoData_Message {
            get {
                return ResourceManager.GetString("FilterTasks_NoData_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success_Message_Title {
            get {
                return ResourceManager.GetString("Success_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error -Message.
        /// </summary>
        internal static string System_Error_Message_Title {
            get {
                return ResourceManager.GetString("System_Error_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal update failed.
        /// </summary>
        internal static string UpdateGoal_Fail_Message {
            get {
                return ResourceManager.GetString("UpdateGoal_Fail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal updated succesfully.
        /// </summary>
        internal static string UpdateGoal_Success_Message {
            get {
                return ResourceManager.GetString("UpdateGoal_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task update failed.
        /// </summary>
        internal static string UpdateTask_Fail_Message {
            get {
                return ResourceManager.GetString("UpdateTask_Fail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task updated succesfully.
        /// </summary>
        internal static string UpdateTask_Success_Message {
            get {
                return ResourceManager.GetString("UpdateTask_Success_Message", resourceCulture);
            }
        }
    }
}
